// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux; // ✅ fixed
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCreZeet1CAj0wBk1DUevCQez0nWflXd_k',
    appId: '1:616155691068:web:18af85f145e71f13e4eb39',
    messagingSenderId: '616155691068',
    projectId: 'commit-to-learn',
    authDomain: 'commit-to-learn.firebaseapp.com',
    storageBucket: 'commit-to-learn.firebasestorage.app',
    measurementId: 'G-D4FRC87H40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe2SDeMAnjw0QTPlc3lnnMRA4ZCtmAb0g',
    appId: '1:616155691068:android:c0ed9cc9a25c3db8e4eb39',
    messagingSenderId: '616155691068',
    projectId: 'commit-to-learn',
    storageBucket: 'commit-to-learn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbsOuPy9Xt6fg273NBy8BYNEIILjAiUs',
    appId: '1:616155691068:ios:2befba2be8fd3139e4eb39',
    messagingSenderId: '616155691068',
    projectId: 'commit-to-learn',
    storageBucket: 'commit-to-learn.firebasestorage.app',
    iosClientId: '616155691068-b4l0i0vg7m4k2g4ngr93mnngvke7eapi.apps.googleusercontent.com',
    iosBundleId: 'com.example.commitToLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpbsOuPy9Xt6fg273NBy8BYNEIILjAiUs',
    appId: '1:616155691068:ios:2befba2be8fd3139e4eb39',
    messagingSenderId: '616155691068',
    projectId: 'commit-to-learn',
    storageBucket: 'commit-to-learn.firebasestorage.app',
    iosClientId: '616155691068-b4l0i0vg7m4k2g4ngr93mnngvke7eapi.apps.googleusercontent.com',
    iosBundleId: 'com.example.commitToLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCreZeet1CAj0wBk1DUevCQez0nWflXd_k',
    appId: '1:616155691068:web:b931d0989b3fe669e4eb39',
    messagingSenderId: '616155691068',
    projectId: 'commit-to-learn',
    authDomain: 'commit-to-learn.firebaseapp.com',
    storageBucket: 'commit-to-learn.firebasestorage.app',
    measurementId: 'G-VG1P6PBDN6',
  );

  // Linux uses the web configuration (Firebase Linux desktop uses web SDK)
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCreZeet1CAj0wBk1DUevCQez0nWflXd_k',
    appId: '1:616155691068:web:18af85f145e71f13e4eb39',
    messagingSenderId: '616155691068',
    projectId: 'commit-to-learn',
    authDomain: 'commit-to-learn.firebaseapp.com',
    storageBucket: 'commit-to-learn.firebasestorage.app',
    measurementId: 'G-D4FRC87H40',
  );
}
